# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Gratzi"
description: > # this means to ignore newlines until "email:"
   Deepening human connection.

email: augman@gmail.com
#blog logo
logo: "/assets/images/UnicornCosmic.svg"
# blog cover
cover: "/assets/images/SW_Mcqueen.jpg"

name: 'Augustin Bralley'
author: 'Augustin Bralley'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://www.gratzi.us" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@augustinbralley'

#fill in disqus shortname to use disqus
disqus: gratzius

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/augustinbralley
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/gratzi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
